### ISSUE TITLE
Support groupChar at the field level

### ISSUE THREAD

**Issue by gperonato** [rgieseke/pandas-datapackage-reader#20]
The `groupChar` [seems](https://specs.frictionlessdata.io/table-schema/#types-and-formats) a property of a numeric field rather than a schema parameter, as it is implemented right now. It would be nice to have the field level implementation.

**Comment by rgieseke** [comment]
Would you like to create a PR for that?

**Comment by gperonato** [comment]
I cannot promise that, but it's on my to-do list

**Comment by gperonato** [comment]
Here it is https://github.com/rgieseke/pandas-datapackage-reader/pull/22

**Comment by gperonato** [comment]
Done.

**Comment by rgieseke** [comment]
Released as 0.18.0
